### ISSUE TITLE
Fresh install - error on youtube-download.pl '"' expected, at character offset 1 (before "args:{raw_player_res...")

### ISSUE THREAD

**Issue by TyRoden** [xaicron/p5-www-youtube-download#66] opened 2022-02-16 18:46 UTC
'"' expected, at character offset 1 (before "args:{raw_player_res...") at /usr/local/share/perl/5.26.1/WWW/YouTube/Download.pm line 299

This is in the response, and the download fails.

**Comment by oalders** [comment] 2022-02-16 18:55
Sounds like this is related to #65. I'm guessing some output changed and the logic here hasn't kept up. If anyone is motivated to fix it, I'm happy to look at pull requests.

**Comment by oalders** [comment] 2023-01-22 18:56
Closing as it's a duplicate of #65 and this module will remain broken until someone submits a PR to fix it. However, https://github.com/yt-dlp/yt-dlp is a great alternative.

**Closed by oalders** 2023-01-22 18:56 UTC
