### ISSUE TITLE
'"' expected, at character offset 1 (before "args:{raw_player_res...") at C:/Strawberry/perl/site/lib/WWW/YouTube/Download.pm line 298.

### ISSUE THREAD

**Issue by chinkuocr** [xaicron/p5-www-youtube-download#67] opened 2023-01-22 04:49 UTC
use WWW::YouTube::Download;
my $client = WWW::YouTube::Download->new;

$url = "https://www.youtube.com/watch?v=he_9tKsP84Q";
$video_id = $client->video_id($url);
$client->download($video_id);

I got the error below: 
'"' expected, at character offset 1 (before "args:{raw_player_res...") at C:/Strawberry/perl/site/lib/WWW/YouTube/Download.pm line 298.

**Comment by oalders** [comment] 2023-01-22 18:57
Thanks for your report. I'm closing as it's a duplicate of #65 and this module will remain broken until someone submits a PR to fix it. However, https://github.com/yt-dlp/yt-dlp is a great alternative.

**Closed by oalders** 2023-01-22 18:57 UTC
